#!/usr/bin/env python3
"""Regenerate the nmail platform icons from resources/nmail-logo.png.

    python3 resources/make_icons.py

Produces:
    resources/nmail.ico            Windows: .rc resource + NSIS installer icon
    resources/nmail.icns           macOS:   nmail.app/Contents/Resources
    resources/icons/nmail-<n>.png  Linux:   hicolor icon theme
    nmail/nmail_icon.h             embedded PNGs for glfwSetWindowIcon()

Only needed when the logo changes; the outputs are checked in so a normal
build (and a Windows or macOS build, which may not have Pillow) never runs it.
"""

import io
import os
import struct
import sys

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow is required: pip install Pillow")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "resources", "nmail-logo.png")

# Windows tolerates any set; these are the sizes Explorer actually asks for.
ICO_SIZES = [16, 24, 32, 48, 64, 128, 256]

# Linux hicolor theme directories.
PNG_SIZES = [16, 24, 32, 48, 64, 128, 256, 512]

# Sizes glfwSetWindowIcon() picks between for the title bar and task switcher.
EMBED_SIZES = [16, 32, 48]

# PNG-backed .icns chunk types.  All of these have been understood since OS X
# 10.7, so they are safe on 10.12; the older RLE types are not worth carrying.
ICNS_TYPES = [
    (b"icp4", 16), (b"icp5", 32), (b"ic11", 32), (b"ic12", 64),
    (b"ic07", 128), (b"ic13", 256), (b"ic08", 256), (b"ic14", 512),
    (b"ic09", 512), (b"ic10", 1024),
]


def scaled(master, size):
    return master.resize((size, size), Image.LANCZOS)


def png_bytes(img):
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def write_icns(master, path):
    chunks = b""
    for ostype, size in ICNS_TYPES:
        data = png_bytes(scaled(master, size))
        chunks += ostype + struct.pack(">I", len(data) + 8) + data
    with open(path, "wb") as f:
        f.write(b"icns" + struct.pack(">I", len(chunks) + 8) + chunks)


def write_header(master, path):
    lines = [
        "/* Generated by resources/make_icons.py -- do not edit by hand.",
        " * nmail logo as PNG blobs, decoded at startup for glfwSetWindowIcon(). */",
        "#pragma once",
        "#include <stddef.h>",
        "",
    ]
    names = []
    for size in EMBED_SIZES:
        data = png_bytes(scaled(master, size))
        name = "nmail_icon_%d_png" % size
        names.append((name, len(data)))
        lines.append("static const unsigned char %s[%d] = {" % (name, len(data)))
        for i in range(0, len(data), 16):
            row = ", ".join("0x%02x" % b for b in data[i:i + 16])
            lines.append("    " + row + ",")
        lines.append("};")
        lines.append("")

    lines.append("struct NmailIconBlob { const unsigned char *data; size_t size; };")
    lines.append("static const struct NmailIconBlob nmail_icon_pngs[] = {")
    for name, size in names:
        lines.append("    { %s, %d }," % (name, size))
    lines.append("};")
    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))


def main():
    if not os.path.exists(SRC):
        sys.exit("missing %s" % SRC)
    master = Image.open(SRC).convert("RGBA")
    if master.size != (1024, 1024):
        print("note: master is %dx%d, expected 1024x1024" % master.size)

    # bitmap_format="bmp" keeps every entry as an uncompressed DIB.  It costs
    # ~350K over PNG-compressed entries, but PNG-in-ICO needs Vista+ and trips
    # up some NSIS versions, and neither is worth debugging on a release build.
    ico = os.path.join(ROOT, "resources", "nmail.ico")
    master.save(ico, format="ICO", sizes=[(s, s) for s in ICO_SIZES],
                bitmap_format="bmp")
    print("wrote %s (%d sizes)" % (ico, len(ICO_SIZES)))

    icns = os.path.join(ROOT, "resources", "nmail.icns")
    write_icns(master, icns)
    print("wrote %s (%d entries)" % (icns, len(ICNS_TYPES)))

    icon_dir = os.path.join(ROOT, "resources", "icons")
    os.makedirs(icon_dir, exist_ok=True)
    for size in PNG_SIZES:
        p = os.path.join(icon_dir, "nmail-%d.png" % size)
        scaled(master, size).save(p, format="PNG", optimize=True)
    print("wrote %s/nmail-{%s}.png" % (icon_dir,
                                       ",".join(str(s) for s in PNG_SIZES)))

    hdr = os.path.join(ROOT, "nmail", "nmail_icon.h")
    write_header(master, hdr)
    print("wrote %s (%s px)" % (hdr, ", ".join(str(s) for s in EMBED_SIZES)))


if __name__ == "__main__":
    main()
